N26/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>language of the customer 
in ISO 639-1 Code (assume we only allow en and de, everything else falls back to en). 
This field cannot be null.</description>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>EN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Customer product information</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_date__c</fullName>
        <description>the date of when a next 
survey should be sent. This field can be null.</description>
        <label>Survey date</label>
        <type>Date</type>
    </fields>
</CustomObject>

N26/src/objects/Product_Inventory__c.object
<CustomObject>
    <description>Product inventory a junction object to hold Contacts and Product via Many-to-Many relationships</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact owning the product</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Inventories</relationshipLabel>
        <relationshipName>Product_Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <description>Actual Product linked to contact</description>
        <label>Products</label>
        <referenceTo>Products__c</referenceTo>
        <relationshipLabel>Product Inventories</relationshipLabel>
        <relationshipName>Product_Inventories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <label>Product Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

N26/src/objects/Products__c.object
<CustomObject>
    <description>Customer product information</description>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <description>ATM Fee in other currencies for the product</description>
        <label>ATM Fee in other currencies</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <description>Cost per Calendar Month for the product</description>
        <label>Cost per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

N26/src/classes/ProductsControllerTest.cls
/* Test class for ProductController 
    Here I created one record for account, contact,products and products inventory
    we can also created the testing for bulk records(200) from for loop and perform testing.
*/

@isTest
private class ProductsControllerTest {

    @testSetup static void setup() {
        Account a = new Account(Name='N26Customer');
        insert a;
        
        Contact con = new Contact(Email = 'balaji.munirathinam@t-systems.com',Survey_Date__c = Date.today() ,AccountId = a.Id, LastName='james', language__c = 'EN', Home_Country__c = 'EN');
        insert con;
        
        Case c = new Case(AccountId = a.Id, ContactId =con.id, Product__c ='GC1040', Type='Mechanical', origin='Email', status='New');
        insert c;
        
        Products__c p = new Products__c(Name='Standard_N27_UK', Product_Type__c = 'Standard', Country__c = 'DE',
        Cost_per_Calendar_Month__c=0.00,ATM_Fee_in_other_currencies__c='Free', Card_Replacement_Cost__c= 6);
        
        insert p;
        
        Product_Inventory__c pi = new Product_Inventory__c(Name='Standard_N27_UK', Contact__c = con.Id, Products__c = p.Id);
        insert pi;
    }
    
    static testMethod void runPositiveInsertTestCases() {
        
        //Set up user
        User u1 = [SELECT Id FROM User WHERE Alias='BM'];
        Case c = [Select Id FROM CASE Where Product__c ='GC1040' limit 1];
        contact con = [Select Id, lastName, survey_date__c From Contact WHERE LastName='james' limit 1];
        List<Products__c> finalProdsCaseId = new list<Products__c>();
        List<Products__c> finalProdsContactId = new list<Products__c>();
        //Run As U1
        System.RunAs(u1) {
            System.debug('Insert one child : single record validation)');
            ProductsController prdCon = new ProductsController();
            finalProdsCaseId = ProductsController.getProductsDetails(c.Id);
            finalProdsContactId = ProductsController.getProductsContactId(con.Id); 
            System.assertNotEquals(null, finalProdsCaseId);
            System.assertNotEquals(null, finalProdsContactId);
        }
    }
    
    static testMethod void runBatchTestCases() {
        
        //Set up user
        User u1 = [SELECT Id FROM User WHERE Alias='BM'];
        list<Contact> con = [Select Id, Email,Name,Home_Country__c,language__c ,LastName, survey_date__c From Contact WHERE LastName='james' limit 1];
        //Run As U1
        System.RunAs(u1) {
            Test.startTest();
            ContactSurveyEmailbatch surveymail = new ContactSurveyEmailbatch();
            Database.QueryLocator ql = surveymail.start(null);
            Database.BatchableContext BC;
            surveymail.execute(null,con);
            contact c = [Select Id, lastName, survey_date__c From Contact WHERE LastName='james' limit 1];
            System.assertEquals(null, c.survey_date__c);
        }
    }
}