N26/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>language of the customer 
in ISO 639-1 Code (assume we only allow en and de, everything else falls back to en). 
This field cannot be null.</description>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Customer product information</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

N26/src/objects/Product_Inventory__c.object
<CustomObject>
    <description>Product inventory a junction object to hold Contacts and Product via Many-to-Many relationships</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact owning the product</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Inventories</relationshipLabel>
        <relationshipName>Product_Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <description>Actual Product linked to contact</description>
        <label>Products</label>
        <referenceTo>Products__c</referenceTo>
        <relationshipLabel>Product Inventories</relationshipLabel>
        <relationshipName>Product_Inventories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <label>Product Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

N26/src/objects/Products__c.object
<CustomObject>
    <description>Customer product information</description>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <description>ATM Fee in other currencies for the product</description>
        <label>ATM Fee in other currencies</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <description>Cost per Calendar Month for the product</description>
        <label>Cost per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

N26/src/classes/ProductsController.cls
public class ProductsController {
  @AuraEnabled
    public static List<Products__c> getProductsDetails(Id caseId) {
        List<Products__c> allProductslst = new List<Products__c>();
        Case c = [Select Id, AccountId, CaseNumber, ContactId FROM Case Where Id=:caseId];
        if(c.ContactId !=null){
           allProductslst = finalProducts(c.contactId);
        }
        return allProductslst;   
    }
    private static list<Products__c> finalProducts(Id ContactId){
        List<Products__c> productsList = new List<Products__c>();
        List<Id> productsIds = new List<Id>();
        list<Product_Inventory__c>  prdInventorylist  = 
          [Select Name,Contact__r.Product__c,Contact__r.Home_Country__c,
            Contact__c,Products__c, Products__r.Country__c,Products__r.Product_Type__c
           FROM Product_Inventory__c WHERE Contact__c=:ContactId];
		
        	System.debug('TOTALPIs'+prdInventorylist);
        
        	For(Product_Inventory__c pi : prdInventorylist){
                if(pi.Contact__r.Product__c == 'All'){
                        productsIds.add(pi.Products__c);
                }
               else if(pi.Contact__r.Product__c == pi.Products__r.Product_Type__c &&
                    pi.Contact__r.Home_Country__c== pi.Products__r.Country__c) {
                        productsIds.add(pi.Products__c);
                }
            }
        System.debug('TotalproductsIds'+productsIds);
            For(Products__c p : [SELECT id,Name,Card_Replacement_Cost__c,Product_Type__c,Country__c,
                                        ATM_Fee_in_other_currencies__c,Cost_per_Calendar_Month__c
                                FROM Products__c
                                WHERE Id IN:productsIds]){
            productsList.add(p);
        }
        System.debug('Totalproductuctslist'+productsList);
        return productsList;
    }
    @AuraEnabled
    public static List<Products__c> getProductsContactId(Id ContactId) {
        List<Products__c> finalProdlst = new List<Products__c>();
        if(ContactId !=null){
            finalProdlst = finalProducts(contactId);
        }
         System.debug('TotalFinalproductuctslist----'+finalProdlst);
        return finalProdlst;   
    }  
}